### ISSUE TITLE
Migrate metadata from `setup.py` to `pyproject.toml`

### ISSUE THREAD

**Issue by fabiobarkoski** [jjeanjacques10/pymangaj#3]
According to [setuptools](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#beta), it's recommended not to use the `setup.py` to declare the metadata. If it's ok, I can make the migration and add the package dependencies inside the metadata file, in that way will be easier to declare the metadata and handle the package dependencies, e.g. declare the test dependencies outside of the core dependencies of the package.

**Comment by jjeanjacques10** [comment]
It's okay to change the setup setup! I'll read the documentation on setuptools recommendations. It was the first time I created a lib, so I got the first way I found to configure and publish. Any contribution will be welcome!

**Comment by fabiobarkoski** [comment]
Sure. I'll make the change, and as soon as I finish I'll make the PR :)

**Comment by fabiobarkoski** [comment]
I also think that's a good idea to document the way to install the test dependencies for those who want to contribute.
